"""incident_foundation"""

import sqlalchemy as sa

from alembic import op

revision = "0005_incident_foundation"
down_revision = "0004_correlation_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_key", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("grouping_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("summary", sa.String(length=2048), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "disposition", sa.String(length=32), server_default="UNDETERMINED", nullable=False
        ),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_calculation_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("promotion_score_threshold", sa.Integer(), nullable=False),
        sa.Column("promotion_confidence_threshold", sa.String(length=16), nullable=False),
        sa.Column("evidence_window_seconds", sa.Integer(), nullable=False),
        sa.Column("first_evidence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_evidence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'RESOLVED' AND closed_at IS NOT NULL) OR "
            "(status != 'RESOLVED' AND closed_at IS NULL)",
            name=op.f("ck_incidents_valid_closed_at"),
        ),
        sa.CheckConstraint(
            "(status = 'RESOLVED' AND disposition != 'UNDETERMINED') OR (status != 'RESOLVED')",
            name=op.f("ck_incidents_valid_resolved_disposition"),
        ),
        sa.CheckConstraint(
            "confidence IN ('medium', 'high')", name=op.f("ck_incidents_valid_confidence")
        ),
        sa.CheckConstraint(
            "disposition IN ('UNDETERMINED', 'BENIGN', 'FALSE_POSITIVE', 'CONFIRMED_THREAT')",
            name=op.f("ck_incidents_valid_disposition"),
        ),
        sa.CheckConstraint(
            "severity IN ('informational', 'low', 'medium', 'high', 'critical')",
            name=op.f("ck_incidents_valid_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'INVESTIGATING', 'RESOLVED')",
            name=op.f("ck_incidents_valid_status"),
        ),
        sa.CheckConstraint(
            "evidence_window_seconds >= 1 AND evidence_window_seconds <= 86400",
            name=op.f("ck_incidents_valid_evidence_window_seconds"),
        ),
        sa.CheckConstraint(
            "last_evidence_at >= first_evidence_at", name=op.f("ck_incidents_valid_evidence_bounds")
        ),
        sa.CheckConstraint(
            "length(grouping_key) = 64", name=op.f("ck_incidents_valid_grouping_key_length")
        ),
        sa.CheckConstraint(
            "length(incident_key) = 64", name=op.f("ck_incidents_valid_incident_key_length")
        ),
        sa.CheckConstraint("policy_version > 0", name=op.f("ck_incidents_valid_policy_version")),
        sa.CheckConstraint(
            "promotion_score_threshold >= 0 AND promotion_score_threshold <= 100",
            name=op.f("ck_incidents_valid_promotion_score_threshold"),
        ),
        sa.CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100", name=op.f("ck_incidents_valid_risk_score")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_incidents_valid_version")),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name="fk_incidents_device_id_devices", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("incident_key", name="uq_incidents_incident_key"),
    )
    op.create_index(
        "ix_incidents_device_status_last_evidence",
        "incidents",
        ["device_id", "status", "last_evidence_at"],
        unique=False,
    )
    op.create_index(
        "ix_incidents_grouping_last_evidence",
        "incidents",
        ["device_id", "policy_id", "policy_version", "grouping_key", "last_evidence_at"],
        unique=False,
    )
    op.create_index(
        "ix_incidents_policy_status_last_evidence",
        "incidents",
        ["policy_id", "status", "last_evidence_at"],
        unique=False,
    )
    op.create_table(
        "incident_correlation_candidates",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["correlation_candidates.id"],
            name="fk_incident_candidates_candidate",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name="fk_incident_candidates_incident",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "incident_id", "candidate_id", name=op.f("pk_incident_correlation_candidates")
        ),
        sa.UniqueConstraint("candidate_id", name="uq_incident_correlation_candidates_candidate_id"),
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="fk_incident_events_event", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name="fk_incident_events_incident",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("incident_id", "event_id", name=op.f("pk_incident_events")),
    )
    op.create_table(
        "incident_status_transitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("from_disposition", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("to_disposition", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=256), nullable=True),
        sa.Column("reason", sa.String(length=2048), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("incident_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(actor_type = 'system' AND actor_id IS NULL) OR "
            "(actor_type = 'operator' AND actor_id IS NOT NULL)",
            name=op.f("ck_incident_status_transitions_valid_actor_id"),
        ),
        sa.CheckConstraint(
            "actor_type IN ('system', 'operator')",
            name=op.f("ck_incident_status_transitions_valid_actor_type"),
        ),
        sa.CheckConstraint(
            "incident_version > 0",
            name=op.f("ck_incident_status_transitions_valid_incident_version"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name="fk_incident_status_transitions_incident_id_incidents",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_status_transitions")),
    )
    op.create_index(
        "ix_incident_status_transitions_timeline",
        "incident_status_transitions",
        ["incident_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_table(
        "incident_detections",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("detection_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detections.id"],
            name="fk_incident_detections_detection",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name="fk_incident_detections_incident",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("incident_id", "detection_id", name=op.f("pk_incident_detections")),
    )
    op.drop_constraint(
        op.f("ck_correlation_candidates_ck_correlation_candidates_val_176d"),
        "correlation_candidates",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_correlation_candidates_ck_correlation_candidates_val_755a"),
        "correlation_candidates",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_correlation_candidates_ck_correlation_candidates_val_a40a"),
        "correlation_candidates",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_correlation_candidates_valid_aggregate_score"),
        "correlation_candidates",
        "aggregate_score >= 0 AND aggregate_score <= 100",
    )
    op.create_check_constraint(
        op.f("ck_correlation_candidates_valid_confidence"),
        "correlation_candidates",
        "confidence IN ('low', 'medium', 'high')",
    )
    op.create_check_constraint(
        op.f("ck_correlation_candidates_valid_correlation_key_length"),
        "correlation_candidates",
        "length(correlation_key) = 64",
    )
    op.drop_constraint(
        op.f("ck_detections_ck_detections_valid_score_contribution"), "detections", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_detections_valid_score_contribution"),
        "detections",
        "score_contribution >= 0 AND score_contribution <= 100",
    )
    op.drop_constraint(op.f("uq_devices_external_id"), "devices", type_="unique")
    op.drop_index(op.f("ix_devices_external_id"), table_name="devices")
    op.create_index(op.f("ix_devices_external_id"), "devices", ["external_id"], unique=True)
    op.drop_constraint(op.f("ck_events_ck_events_positive_schema_version"), "events", type_="check")
    op.create_check_constraint(
        op.f("ck_events_positive_schema_version"), "events", "schema_version > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_events_positive_schema_version"), "events", type_="check")
    op.create_check_constraint(
        op.f("ck_events_ck_events_positive_schema_version"), "events", "schema_version > 0"
    )
    op.drop_index(op.f("ix_devices_external_id"), table_name="devices")
    op.create_index(op.f("ix_devices_external_id"), "devices", ["external_id"], unique=False)
    op.create_unique_constraint(
        op.f("uq_devices_external_id"),
        "devices",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("ck_detections_valid_score_contribution"), "detections", type_="check")
    op.create_check_constraint(
        op.f("ck_detections_ck_detections_valid_score_contribution"),
        "detections",
        "score_contribution >= 0 AND score_contribution <= 100",
    )
    op.drop_constraint(
        op.f("ck_correlation_candidates_valid_correlation_key_length"),
        "correlation_candidates",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_correlation_candidates_valid_confidence"), "correlation_candidates", type_="check"
    )
    op.drop_constraint(
        op.f("ck_correlation_candidates_valid_aggregate_score"),
        "correlation_candidates",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_correlation_candidates_ck_correlation_candidates_val_a40a"),
        "correlation_candidates",
        "aggregate_score >= 0 AND aggregate_score <= 100",
    )
    op.create_check_constraint(
        op.f("ck_correlation_candidates_ck_correlation_candidates_val_755a"),
        "correlation_candidates",
        "length(correlation_key::text) = 64",
    )
    op.create_check_constraint(
        op.f("ck_correlation_candidates_ck_correlation_candidates_val_176d"),
        "correlation_candidates",
        "confidence::text = ANY (ARRAY['low'::character varying, "
        "'medium'::character varying, 'high'::character varying]::text[])",
    )
    op.drop_table("incident_detections")
    op.drop_index(
        "ix_incident_status_transitions_timeline", table_name="incident_status_transitions"
    )
    op.drop_table("incident_status_transitions")
    op.drop_table("incident_events")
    op.drop_table("incident_correlation_candidates")
    op.drop_index("ix_incidents_policy_status_last_evidence", table_name="incidents")
    op.drop_index("ix_incidents_grouping_last_evidence", table_name="incidents")
    op.drop_index("ix_incidents_device_status_last_evidence", table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
